### PR TITLE
Replace  gulp util

### PR DESCRIPTION
**Pull request by EugeneBalabai**
@nymo I replaced gulp-utils. check please. I was guided by this article https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

Maybe you have something to add

### CODE REVIEW

**Comment by EugeneBalabai** [comment]
Hello @nymo 
How are you? We can update the plugin?

**Comment by nymo** [comment]
Hi @EugeneBalabai,
sorry for the delay had no time until now. Checked you're changes and they look good thank you. Will tag version 2.0.0 and update the npm package.

**Comment by EugeneBalabai** [comment]
@nymo, thanks man
Maybe you have ideas for improving the plugin? Maybe the features you would like to add? I want to improve my skills and do it with the benefit

**Comment by nymo** [comment]
Well as you can see I forked this package also from someone else and added some extensions/improvements to it which were missing for me. I'm happy if someone else could also benefit from this improvements. But I did this because I had a use case for this library and have to say that at the moment it is running as expected and I miss nothing anymore.
But if you have any ideas for improvements or new features feel free to open up some merge requests. As long as the library is not breaking or changing it's base functionality I'm pretty sure we can add this stuff here :)

**Pull request merged**
